% Example state matrix: Two states; Chase lights to exit

sma = NewStateMatrix();

sma = AddState(sma, 'Name', 'Port1Lit', ...
    'Timer', 0,...
    'StateChangeConditions', {'Port1In', 'Port3Lit'},...
    'OutputActions', {'PWM1', 255});
sma = AddState(sma, 'Name', 'Port3Lit', ...
    'Timer', 0,...
    'StateChangeConditions', {'Port3In', 'exit'},...
    'OutputActions', {'PWM3', 255});